<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class GynecologistSeeder extends Seeder
{
    public function run(): void
    {
        $gynecologists = [
            [
                'first_name' => 'Fatima',
                'last_name' => 'Benali',
                'speciality' => 'Gynécologie-Obstétrique',
                'license_number' => 'MA-GYN-001',
                'email' => 'f.benali@feminasante.ma',
                'phone' => '+212 522 123 456',
                'adress' => '15 Rue Ibn Batouta, Maarif',
                'city' => 'Casablanca',
                'postal_code' => '20100',
                'consultation_type' => json_encode(['in_person', 'online']),
                'consultation_duration' => 30,
                'consultation_fee' => 350.00,
                'bio' => 'Spécialiste en gynécologie-obstétrique avec 15 ans d\'expérience. Diplômée de la Faculté de Médecine de Casablanca, elle prend en charge le suivi de grossesse, la contraception et les pathologies gynécologiques.',
                'languages_spoken' => json_encode(['Français', 'Arabe', 'Darija']),
                'rating' => 4.8,
                'review_count' => 124,
                'is_active' => 1,
            ],
            [
                'first_name' => 'Nadia',
                'last_name' => 'El Idrissi',
                'speciality' => 'Gynécologie médicale',
                'license_number' => 'MA-GYN-002',
                'email' => 'n.elidrissi@feminasante.ma',
                'phone' => '+212 537 654 321',
                'adress' => '8 Avenue Mohammed V',
                'city' => 'Rabat',
                'postal_code' => '10000',
                'consultation_type' => json_encode(['in_person']),
                'consultation_duration' => 45,
                'consultation_fee' => 400.00,
                'bio' => 'Gynécologue médicale spécialisée dans la ménopause, l\'endométriose et la fertilité. Formatrice universitaire et membre de la Société Marocaine de Gynécologie.',
                'languages_spoken' => json_encode(['Français', 'Arabe', 'Anglais']),
                'rating' => 4.9,
                'review_count' => 89,
                'is_active' => 1,
            ],
            [
                'first_name' => 'Samira',
                'last_name' => 'Tazi',
                'speciality' => 'Obstétrique',
                'license_number' => 'MA-GYN-003',
                'email' => 's.tazi@feminasante.ma',
                'phone' => '+212 535 789 012',
                'adress' => '22 Boulevard Zerktouni',
                'city' => 'Fès',
                'postal_code' => '30000',
                'consultation_type' => json_encode(['in_person', 'online']),
                'consultation_duration' => 30,
                'consultation_fee' => 300.00,
                'bio' => 'Obstétricienne passionnée par l\'accompagnement des femmes enceintes. Expertise en grossesses à risque et accouchement physiologique.',
                'languages_spoken' => json_encode(['Français', 'Arabe']),
                'rating' => 4.7,
                'review_count' => 203,
                'is_active' => 1,
            ],
            [
                'first_name' => 'Houda',
                'last_name' => 'Mansouri',
                'speciality' => 'Gynécologie-Obstétrique',
                'license_number' => 'MA-GYN-004',
                'email' => 'h.mansouri@feminasante.ma',
                'phone' => '+212 524 345 678',
                'adress' => '5 Rue de la Liberté, Guéliz',
                'city' => 'Marrakech',
                'postal_code' => '40000',
                'consultation_type' => json_encode(['in_person']),
                'consultation_duration' => 30,
                'consultation_fee' => 320.00,
                'bio' => 'Gynécologue-obstétricienne avec une approche centrée sur le bien-être de la femme. Spécialisée en contraception, infections gynécologiques et suivi prénatal.',
                'languages_spoken' => json_encode(['Français', 'Arabe', 'Darija']),
                'rating' => 4.6,
                'review_count' => 67,
                'is_active' => 1,
            ],
            [
                'first_name' => 'Leila',
                'last_name' => 'Chraibi',
                'speciality' => 'Fertilité & Procréation',
                'license_number' => 'MA-GYN-005',
                'email' => 'l.chraibi@feminasante.ma',
                'phone' => '+212 522 987 654',
                'adress' => '31 Rue Abou Inane, CIL',
                'city' => 'Casablanca',
                'postal_code' => '20300',
                'consultation_type' => json_encode(['in_person', 'online']),
                'consultation_duration' => 60,
                'consultation_fee' => 500.00,
                'bio' => 'Spécialiste en procréation médicalement assistée (PMA) et fertilité. Accompagne les couples dans leur parcours vers la parentalité avec empathie et expertise.',
                'languages_spoken' => json_encode(['Français', 'Arabe', 'Anglais', 'Espagnol']),
                'rating' => 4.9,
                'review_count' => 156,
                'is_active' => 1,
            ],
            [
                'first_name' => 'Zineb',
                'last_name' => 'Ouhssine',
                'speciality' => 'Gynécologie-Obstétrique',
                'license_number' => 'MA-GYN-006',
                'email' => 'z.ouhssine@feminasante.ma',
                'phone' => '+212 539 111 222',
                'adress' => '14 Avenue des FAR',
                'city' => 'Tanger',
                'postal_code' => '90000',
                'consultation_type' => json_encode(['in_person']),
                'consultation_duration' => 30,
                'consultation_fee' => 280.00,
                'bio' => 'Gynécologue engagée pour la santé des femmes du nord du Maroc. Consultations en cabinet et participation à des programmes de dépistage régionaux.',
                'languages_spoken' => json_encode(['Français', 'Arabe', 'Espagnol']),
                'rating' => 4.5,
                'review_count' => 44,
                'is_active' => 1,
            ],
            [
                'first_name' => 'Amina',
                'last_name' => 'Karimi',
                'speciality' => 'Gynécologie oncologique',
                'license_number' => 'MA-GYN-007',
                'email' => 'a.karimi@feminasante.ma',
                'phone' => '+212 522 444 555',
                'adress' => '9 Rue Jean Jaurès, Gauthier',
                'city' => 'Casablanca',
                'postal_code' => '20050',
                'consultation_type' => json_encode(['in_person', 'online']),
                'consultation_duration' => 45,
                'consultation_fee' => 450.00,
                'bio' => 'Onco-gynécologue spécialisée dans le dépistage et le traitement des cancers gynécologiques (col, ovaires, endomètre). Membre de la Société Marocaine d\'Oncologie.',
                'languages_spoken' => json_encode(['Français', 'Arabe', 'Anglais']),
                'rating' => 4.8,
                'review_count' => 78,
                'is_active' => 1,
            ],
            [
                'first_name' => 'Meriem',
                'last_name' => 'Bousfiha',
                'speciality' => 'Gynécologie-Obstétrique',
                'license_number' => 'MA-GYN-008',
                'email' => 'm.bousfiha@feminasante.ma',
                'phone' => '+212 535 333 444',
                'adress' => '3 Avenue Allal El Fassi',
                'city' => 'Meknès',
                'postal_code' => '50000',
                'consultation_type' => json_encode(['in_person']),
                'consultation_duration' => 30,
                'consultation_fee' => 250.00,
                'bio' => 'Gynécologue-obstétricienne à Meknès, avec une pratique axée sur la santé reproductive de la femme à tous les âges de la vie.',
                'languages_spoken' => json_encode(['Français', 'Arabe', 'Darija']),
                'rating' => 4.4,
                'review_count' => 31,
                'is_active' => 1,
            ],
            [
                'first_name' => 'Khadija',
                'last_name' => 'Alaoui',
                'speciality' => 'Gynécologie médicale',
                'license_number' => 'MA-GYN-009',
                'email' => 'k.alaoui@feminasante.ma',
                'phone' => '+212 537 222 333',
                'adress' => '17 Rue Soussa, Agdal',
                'city' => 'Rabat',
                'postal_code' => '10080',
                'consultation_type' => json_encode(['in_person', 'online']),
                'consultation_duration' => 30,
                'consultation_fee' => 380.00,
                'bio' => 'Gynécologue médicale à Rabat, spécialisée dans le suivi des maladies chroniques féminines, la ménopause et la contraception adaptée.',
                'languages_spoken' => json_encode(['Français', 'Arabe']),
                'rating' => 4.7,
                'review_count' => 95,
                'is_active' => 1,
            ],
            [
                'first_name' => 'Soukaina',
                'last_name' => 'Rharbaoui',
                'speciality' => 'Gynécologie-Obstétrique',
                'license_number' => 'MA-GYN-010',
                'email' => 's.rharbaoui@feminasante.ma',
                'phone' => '+212 528 555 666',
                'adress' => '6 Boulevard Mohammed VI',
                'city' => 'Agadir',
                'postal_code' => '80000',
                'consultation_type' => json_encode(['in_person', 'online']),
                'consultation_duration' => 30,
                'consultation_fee' => 300.00,
                'bio' => 'Gynécologue basée à Agadir, prenant en charge grossesses, pathologies gynécologiques et suivi post-partum dans un cadre bienveillant.',
                'languages_spoken' => json_encode(['Français', 'Arabe', 'Amazigh']),
                'rating' => 4.6,
                'review_count' => 52,
                'is_active' => 1,
            ],
        ];

        foreach ($gynecologists as $gyn) {
            DB::table('gynecologists')->insertOrIgnore([
                ...$gyn,
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }

        $this->command->info('✅ 10 gynecologists seeded.');
    }
}